version: '3.9'

services:
  mongodb:
    image: mongo:7-jammy
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: djamware
      MONGO_INITDB_ROOT_PASSWORD: djAmwAr3
      MONGO_INITDB_DATABASE: study
    ports:
      - "27017:27017"
    networks:
      - school-network

networks:
  school-network:
    name: school-network
    external: true
